requirements:

discovery:
  homeassistant: # Must match discovery preset name
    - topic: "network/bytes_recv"
      payload:
        name: "Network received data"
        icon: "mdi:download"        
        unit_of_measurement: "MB"
    - topic: "network/bytes_sent"
      payload:
        name: "Network sent data"
        icon: "mdi:upload"
        unit_of_measurement: "MB"